USE [BusquedaVehiculos]
GO

INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('aguamarina', 'Aguamarina');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('almendra', 'Almendra');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('amarillo', 'Amarillo');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('amarillo-claro', 'Amarillo Claro');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('anis', 'Anis');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('arena', 'Arena');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul', 'Azul');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul-absoluto', 'Azul Absoluto');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul-andino', 'Azul Andino');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul-celeste', 'Azul Celeste');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul-danubio', 'Azul Danubio');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul-electrico', 'Azul Eléctrico');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul-europa', 'Azul Europa');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul-metalizado', 'Azul Metalizado');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul-oscuro', 'Azul Oscuro');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul-oscuro-metalizado', 'Azul Oscuro Metalizado');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul-perlado', 'Azul Perlado');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul-profundo', 'Azul Profundo');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('azul-tinta', 'Azul Tinta');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('beige', 'Beige');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('beige-metalizado', 'Beige Metalizado');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('berenjena', 'Berenjena');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('bicolor', 'Bicolor');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('blanco', 'Blanco');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('blanco-hueso', 'Blanco Hueso');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('borso', 'Borsó');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('bronce', 'Bronce');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('cafe', 'Café');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('cafe-claro', 'Café Claro');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('celeste', 'Celeste');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('champagne', 'Champagne');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('cobre', 'Cobre');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('crema', 'Crema');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('dorado', 'Dorado');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('estrato-perla', 'Estrato Perla');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris', 'Gris');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-aluminio', 'Gris Aluminio');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-boreal', 'Gris Boreal');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-claro', 'Gris Claro');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-granito', 'Gris Granito');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-intermedio', 'Gris Intermedio');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-metalizado', 'Gris Metalizado');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-neptuno', 'Gris Neptuno');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-noche', 'Gris Noche');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-nube', 'Gris Nube');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-oscuro', 'Gris Oscuro');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-plata', 'Gris Plata');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-plomo', 'Gris Plomo');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('gris-verdoso', 'Gris Verdoso');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('marron', 'Marrón');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('marron-oscuro', 'Marrón Oscuro');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('mostaza', 'Mostaza');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('naranja', 'Naranja');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('negro', 'Negro');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('negro-brillante', 'Negro Brillante');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('negro-mate', 'Negro Mate');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('ocre', 'Ocre');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('oro', 'Oro');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('otro', 'Otro');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('perlado', 'Perlado');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('plata', 'Plata');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('rojo', 'Rojo');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('rojo-berlin', 'Rojo Berlín');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('rojo-ferrari', 'Rojo Ferrari');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('rojo-fuego', 'Rojo Fuego');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('rojo-pasion', 'Rojo Pasión');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('rojo-vivo', 'Rojo Vivo');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('rosado', 'Rosado');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('silice', 'Silice');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('turquesa', 'Turquesa');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('verde', 'Verde');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('verde-amazonas', 'Verde Amazonas');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('verde-andino', 'Verde Andino');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('verde-arrecife', 'Verde Arrecife');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('verde-claro', 'Verde Claro');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('verde-esmeralda', 'Verde Esmeralda');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('verde-metalizado', 'Verde Metalizado');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('verde-oliva', 'Verde Oliva');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('verde-oscuro', 'Verde Oscuro');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('vinotinto', 'Vinotinto');
INSERT INTO TB_VehiculoColor (CodVehiculoColor, DescVehiculoColor) VALUES ('violeta', 'Violeta');
