USE [BusquedaVehiculos]
GO

INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@a4', 'A4');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@100', '100');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@200', '200');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@5000', '5000');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@80', '80');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@a1', 'A1');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@a100', 'A100');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@a3', 'A3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@a5', 'A5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@a6', 'A6');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@a7', 'A7');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@a8', 'A8');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@allroad', 'Allroad');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@gt', 'Gt');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@q3', 'Q3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@q5', 'Q5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@q7', 'Q7');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@r8', 'R8');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@rs', 'Rs');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@s3', 'S3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@s4', 'S4');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@s5', 'S5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@s8', 'S8');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'audi@tt', 'TT');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@100', '100');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@200', '200');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@80', '80');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@a1', 'A1');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@a3', 'A3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@a4', 'A4');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@a5', 'A5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@a6', 'A6');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@a7', 'A7');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@a8', 'A8');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@allroad', 'Allroad');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@q3', 'Q3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@q5', 'Q5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@q7', 'Q7');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@r8', 'R8');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@s3', 'S3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@s5', 'S5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'audi@tt', 'TT');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@1722', 'A3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@1723', 'A4');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@1724', 'A4 Avant');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@1725', 'A6');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@1727', 'A6 Avant');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@1729', 'A8');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@1730', 'TT Roadster');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@2200', 'S4');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@2227', 'S3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@2573', 'Allroad');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@2832', 'Q7');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@2940', 'R8 Coupe');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@2965', 'A5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3002', 'Q5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3068', 'A1');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3095', 'A7 Sportback');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3113', 'RS5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3119', 'A4 Allroad');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3120', 'A5 Sportback');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3122', 'Q3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3197', 'A1 Sportback');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3198', 'A3 Sportback');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3203', 'TT Coupe');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3204', 'TT RS');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3237', 'A6 Allroad');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '361@3247', 'A3 Sedán');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@234', 'A1');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@235', 'A3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@236', 'A4');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@238', 'A5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@239', 'A6');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@244', 'Allroad');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@249', 'Q5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@250', 'Q7');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@251', 'R8');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@255', 'S3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@256', 'S4');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@257', 'S5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@262', 'TT');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '5@7193', 'Q3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@a1', 'A1');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@a3', 'A3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@a4', 'A4');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@a5', 'A5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@a6', 'A6');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@a7', 'A7');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@a8', 'A8');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@allroad', 'Allroad');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@cabrio', 'Cabrio');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@otros-modelos', 'Otros Modelos');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@q3', 'Q3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@q5', 'Q5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@q7', 'Q7');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@r8', 'R8');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@rs4', 'RS4');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@rs5', 'RS5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@s3', 'S3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@s4', 'S4');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@s5', 'S5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'audi@tt', 'TT');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@a1', 'A1');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@a3', 'A3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@a4', 'A4');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@a5', 'A5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@a6', 'A6');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@a7', 'A7');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@a8', 'A8');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@allroad', 'Allroad');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@cabrio', 'Cabrio');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@other', 'Otro');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@q3', 'Q3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@q5', 'Q5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@q7', 'Q7');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@r8', 'R8');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@rs5', 'RS');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@s3', 'S3');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@s4', 'S4');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@s5', 'S5');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@s8', 'S8');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'audi@tt', 'TT');
