USE [BusquedaVehiculos]
GO

INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@106', '106');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@205', '205');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@206', '206');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@206-sw', '206 SW');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@207', '207');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@207-compact', '207 Compact');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@208', '208');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@3008', '3008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@305', '305');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@306', '306');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@307', '307');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@307-sw', '307 SW');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@308', '308');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@403', '403');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@404', '404');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@405', '405');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@406', '406');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@407', '407');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@407-sw', '407 SW');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@408', '408');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@504', '504');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@505', '505');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@508', '508');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@604', '604');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@605', '605');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@607', '607');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@806', '806');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@807', '807');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@grand-raid', 'Grand Raid');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@patagonica', 'Patagonica');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('ALAMAULA', 'MOD', 'peugeot@rcz', 'RCZ');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@106', '106');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@205', '205');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@206', '206');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@207', '207');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@207+compact+xt', '207 COMPACT XT');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@208', '208');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@3008', '3008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@306', '306');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@307', '307');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@308', '308');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@4008', '4008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@403', '403');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@404', '404');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@405', '405');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@406', '406');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@407', '407');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@408', '408');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@5008', '5008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@504', '504');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@504+pick-up', '504 Pick-Up');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@505', '505');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@508', '508');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@604', '604');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@605', '605');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@607', '607');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@806', '806');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@807', '807');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@boxer', 'Boxer');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@expert', 'Expert');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@hoggar', 'Hoggar');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@otros', 'Otros');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@partner', 'Partner');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@partner+patagonica', 'Partner Patagónica');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('AUTOFOCO', 'MOD', 'peugeot@rcz', 'RCZ');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@1883', '106');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@1884', '306');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@1886', '406');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@1887', '504');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@1890', '504 Pick Up');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@1892', '205');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@1893', '206');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@1895', 'Boxer');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@2115', '505');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@2207', 'Expert');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@2268', '404');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@2594', '307');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@2604', '405');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@2699', '807');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@2741', '407');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@2986', '207');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3014', '308');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3040', '3008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3070', 'RCZ');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3071', '408');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3090', 'Hoggar');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3108', '5008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3112', '508');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3159', '308 CC');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3160', '308 GTi');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3180', '208');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3236', '4008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3249', '207 CC');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3250', '208 GTi');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3251', '208 XY');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3264', '207 Compact');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3290', '207 Compact SW');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3291', '207 GTi');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3292', '207 RC');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3335', '308 2015');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3336', '408 2015');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@1894', 'Partner Furgón');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEAUTOS', 'MOD', '385@3252', 'Partner Patagónica');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4847', '106');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4849', '205');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4850', '206');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4853', '207');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4854', '207 Compact');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4855', '3008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4857', '306');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4861', '307');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4866', '308');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4869', '403');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4870', '404');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4871', '405');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4874', '406');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4875', '407');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4877', '504');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4879', '508');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4887', 'Boxer');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4890', 'Expert');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4895', 'Hoggar');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4900', 'Otro Modelo');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4902', 'Partner');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@4903', 'RCZ');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@6808', '408');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@6950', '5008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@7023', '208');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('DEMOTORES', 'MOD', '64@7494', '308 Hatchback');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@106', '106');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@2008', '2008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@205', '205');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@206', '206');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@206-sw', '206 SW');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@207', '207');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@207-sw', '207 Compact');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@208', '208');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@3008', '3008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@306', '306');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@307', '307');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@307-sw', '307 SW');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@308', '308');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@4008', '4008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@405', '405');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@406', '406');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@407', '407');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@407-sw', '407 SW');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@408', '408');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@5008', '5008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@504', '504');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@504-pick-up', '504 Pick Up');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@505', '505');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@508', '508');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@605', '605');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@607', '607');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@806', '806');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@807', '807');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@boxer', 'Boxer');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@expert', 'Expert');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@hoggar', 'Hoggar');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@otros-modelos', 'Otros Modelos');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@partner', 'Partner');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('MERCADOLIBRE', 'MOD', 'peugeot@rcz', 'RCZ');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@106', '106');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@205', '205');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@206', '206');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@206+sw', '206 SW');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@207', '207');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@207+compact', '207 Compact');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@208', '208');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@3008', '3008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@306', '306');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@307', '307');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@307+sw', '307 SW');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@308', '308');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@4008', '4008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@403', '403');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@404', '404');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@405', '405');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@406', '406');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@407', '407');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@408', '408');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@5008', '5008');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@504', '504');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@504+pick', '594 Pick');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@505', '505');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@605', '605');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@boxer', 'Boxer');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@expert', 'Expert');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@hoggar', 'Hoggar');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@otro', 'Otro');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@partner', 'Partner');
INSERT INTO TB_ProviderCatalogoItem (CodProvider, CodCatalogo, CodItemProvider, DescItemProvider) VALUES ('OLX', 'MOD', 'peugeot@rcz', 'RCZ');
