USE [BusquedaVehiculos]
GO

INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '11', '11');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '12', '12');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '18', '18');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '19', '19');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '20', '20');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '21', '21');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '21-nevada', '21 Nevada');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '25', '25');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '30', '30');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '4', '4');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '5', '5');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '6', '6');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', '9', '9');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'clio', 'Clío');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'clio-2', 'Clío 2');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'clio-linea-nueva', 'Clío Linea Nueva');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'clio-mio', 'Clío Mío');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'dauphine', 'Dauphine');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'duster', 'Duster');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'duster-oroch', 'Duster Oroch');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'duster-ph2', 'Duster PH2');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'espace', 'Espace');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'express', 'Express');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'floride', 'Floride');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'fluence', 'Fluence');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'fluence-ph2', 'Fluence PH2');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'fuego', 'Fuego');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'gmc', 'Gmc');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'gordini', 'Gordini');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'grand-scenic', 'Grand Scenic');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'ika', 'Ika');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'kangoo', 'Kangoo');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'kangoo-2', 'Kangoo 2');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'kangoo-break', 'Kangoo Break');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'kangoo-express', 'Kangoo Express');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'kangoo-express-ph3', 'Kangoo Express PH3');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'kangoo-ph3', 'Kangoo PH3');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'koleos', 'Koleos');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'koleos-nueva', 'Koleos Nueva');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'laguna', 'Laguna');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'laguna-2', 'Laguna 2');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'laguna-grand-tour', 'Laguna Grand Tour');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'latitude', 'Latitude');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'logan', 'Logan');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'logan-ii', 'Logan II');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'master', 'Master');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'master-chasis', 'Master Chasis');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'master-furgon', 'Master Furgón');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'megane', 'Megane');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'megane-2', 'Megane 2');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'megane-3', 'Megane 3');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'megane-fase-ii', 'Megane Fase II');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'megane-ii-grand-tour', 'Megane II Grand Tour');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'megane-iii-rs', 'Megane III RS');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'otro', 'Otro');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'rodeo', 'Rodeo');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'safrane', 'Safrane');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'sandero', 'Sandero');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'sandero-fase-ii', 'Sandero Fase II');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'sandero-gt-line', 'Sandero GT line');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'sandero-nuevo-(ii)', 'Sandero Nuevo (II)');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'sandero-stepway', 'Sandero Stepway');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'sandero-stepway-fase-ii', 'Sandero Stepway Fase II');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'sandero-stepway-nuevo-(ii)', 'Sandero Stepway Nuevo (II)');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'scala', 'Scala');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'scenic', 'Scenic');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'scenic-2', 'Scenic 2');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'stepway', 'Stepway');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'symbol', 'Symbol');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'torino', 'Torino');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'trafic', 'Trafic');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'trafic-furgon', 'Trafic Furgón');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('renault', 'twingo', 'Twingo');
