USE [BusquedaVehiculos]
GO

INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', '1500', '1500');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', '1600', '1600');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'amarok', 'Amarok');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'amarok-highline', 'Amarok Highline');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'atlantic', 'Atlantic');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'beetle', 'Beetle');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'bora', 'Bora');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'caddy', 'Caddy');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'carat', 'Carat');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'caribe', 'Caribe');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'cc', 'CC');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'clasico', 'Clasico');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'corsar', 'Corsar');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'crossfox', 'Crossfox');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'escarabajo', 'Escarabajo');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'fol-trend', 'Fol Trend');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'fox', 'Fox');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'fox-2015', 'Fox 2015');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'furgon', 'Furgon');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'gacel', 'Gacel');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'gli', 'GLI');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'gol', 'Gol');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'gol-country', 'Gol Country');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'golf', 'Golf');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'golf-gti', 'Golf GTI');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'golf-variant', 'Golf Variant');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'golf-vii', 'Golf VII');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'golf-vii-variant', 'Golf VII Variant');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'gol-power', 'Gol Power');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'gti', 'GTI');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'iltis', 'Iltis');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'jetta', 'Jetta');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'kombi', 'Kombi');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'lupo', 'Lupo');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'new-beetle', 'New Beetle');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'otro', 'Otro');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'passat', 'Passat');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'passat-cc', 'Passat CC');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'passat-variant', 'Passat Variant');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'pointer', 'Pointer');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'polo', 'Polo');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'polo-classic', 'Polo Classic');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'polo-sedan', 'Polo Sedán');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'quantum', 'Quantum');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'rabbit', 'Rabbit');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'santana', 'Santana');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'saveiro', 'Saveiro');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'scirocco', 'Scirocco');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'sedan', 'Sedan');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'senda', 'Senda');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'sharan', 'Sharan');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'sp-ii', 'SP II');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'suran', 'Suran');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'suran-2015', 'Suran 2015');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'suran-cross', 'Suran Cross');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'tiguan', 'Tiguan');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'touareg', 'Touareg');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'transporter', 'Transporter');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'up!', 'UP!');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'vento', 'Vento');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'vento-2015', 'Vento 2015');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'vento-variant', 'Vento Variant');
INSERT INTO TB_VehiculoSubMarca (CodVehiculoMarca, CodVehiculoSubMarca, DescVehiculoSubMarca) VALUES ('volkswagen', 'voyage', 'Voyage');
